### ISSUE TITLE
Optional field should be use pointer

### ISSUE THREAD

**Issue by fatkun** [oam-dev/admission-controller#5]
# Expect
Compare to kubenetes core/api, optional struct field should be use pointer, such as ```LivenessProbe *Probe```.
We can check this filed is null if not set the field in yaml file.

https://github.com/kubernetes/kubernetes/blob/81af5baff8e958dc8817913ec3c4172028f30122/pkg/apis/core/types.go#L2063-L2069

# Current
LivenessProbe and other field should be optional.
```
type Container struct {
	Name            string       `json:"name"`
	Image           string       `json:"image"`
	Resources       Resources    `json:"resources"`
	Cmd             []string     `json:"cmd"`
	Args            []string     `json:"args"`
	Env             []Env        `json:"env"`
	Config          []ConfigFile `json:"config"`
	Ports           []Port       `json:"ports"`
	LivenessProbe   HealthProbe  `json:"livenessProbe"`
	ReadinessProbe  HealthProbe  `json:"readinessProbe"`
	ImagePullSecret string       `json:"imagePullSecret"`
}
```

**Comment by wonderflow** [comment]
Yes, HealthProbe should use pointer. Not because it's pointer in K8s, just because it's optional in [OAM-spec](https://github.com/oam-dev/spec/blob/master/3.component_model.md#container). We must follow OAM spec.

Welcome to give a PR if you are ready! Thanks!
